swagger: '2.0'
info:
  title: Harmonize Web Application
  description: Connect, do, and harominze your life
  version: 1.0.0
host: localhost:3000
schemes:
  - http
  - https
consumes:
  - application/json
paths:
  '/ping':
    x-swagger-router-controller: root
    get:
      operationId: ping
      summary: Health check path
      responses:
        200:
          description: The server is alive
          schema:
            type: string
        default:
          description: Processing error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      status:
        type: integer
        format: int32
